---
output:
  word_document: default
  html_document: default
---

```{r}
#1/1
rm(list=ls())

probLoaded <-  c(0.01,0.99)

data <-c(2,3,2,6,3,5,6,2,6,6,2,6,6,2,3,6,6,6,5,6,6,5,6,6,6,6,6,4,6,3,3,3,6,6,5,6,6)
# p(positive) , p(negative)
LikelihoodLoaded <- c(1/10,1/10,1/10,1/10,1/10,5/10)
LikelihoodFair<- c(1/6,1/6,1/6,1/6,1/6,1/6)

probLoadedVals <- vector();
i <- (1:6)

ProbabilityLoaded <- ""
for( i in 1:length(data))
{
	probLoadedVals[i] <- probLoaded[1];
	
	denom <- probLoaded[1] * LikelihoodLoaded[data[i]] + probLoaded[2] * LikelihoodFair[data[i]];
	
	probLoaded[1] = probLoaded[1] * LikelihoodLoaded[data[i]] / denom;
	probLoaded[2] = probLoaded[2] * LikelihoodFair[data[i]] / denom;
	
	ProbabilityLoaded <- paste(ProbabilityLoaded,data[i],sep="")
	plot(1:i,probLoadedVals, main = "ProbabilityLoaded",ylim=c(0,1),xlim=c(1,length(data)+1))
	Sys.sleep(.5);
}
```

```{r}
#1/2
rm(list=ls())
probLoaded <-  c(0.05,0.95)

data <-c(2,3,2,6,3,5,6,2,6,6,2,6,6,2,3,6,6,6,5,6,6,5,6,6,6,6,6,4,6,3,3,3,6,6,5,6,6)
# p(positive) , p(negative)
LikelihoodLoaded <- c(1/10,1/10,1/10,1/10,1/10,5/10)
LikelihoodFair<- c(1/6,1/6,1/6,1/6,1/6,1/6)

probLoadedVals <- vector();
i <- (1:6)

ProbabilityLoaded <- ""
for( i in 1:length(data))
{
	probLoadedVals[i] <- probLoaded[1];
	
	denom <- probLoaded[1] * LikelihoodLoaded[data[i]] + probLoaded[2] * LikelihoodFair[data[i]];
	
	probLoaded[1] = probLoaded[1] * LikelihoodLoaded[data[i]] / denom;
	probLoaded[2] = probLoaded[2] * LikelihoodFair[data[i]] / denom;
	
	ProbabilityLoaded <- paste(ProbabilityLoaded,data[i],sep="")
	plot(1:i,probLoadedVals, main = "ProbabilityLoaded",ylim=c(0,1),xlim=c(1,length(data)+1))
	Sys.sleep(.5);
}

```

```{r}
#3/1
#Anusha helped me with this.
rm(list=ls())
probs <- seq(0,1,.001)
plot(probs,dbeta(probs,6,6),ylim = c(0,4))
lines(probs,dbeta(probs,1,1),col="red")

```

```{r}
#3B
plot(probs, dbeta(probs, 7, 7), ylim = c(0,3), col = "green")
lines(probs,dbeta(probs,2,2),col = "blue")
```

```{r}
plot(probs, dbeta(probs, 406, 406), ylim = c(0,3), col = "purple")
lines(probs,dbeta(probs,401,401),col = "red")
```

