```{r}
x <- seq(0,1,.01)
plot(dexp(x,rate = 5)/0.9932621)
```

```{r}
#1B
piOld <- .5
#dbeta( piOld, 40,40 )
numIterations <- 10000
posteiorDist <- vector()

for( i in 1:numIterations )
{
	# our prior with 40 heads and 40 tails
	# our new data with 14 heads and 10 tails
	pOld <- (dexp(x,rate = 5)/0.9932621) * dbinom( 14, 24, piOld )
	
	piNew <- piOld + rnorm(1, 0, sd =0.1);
	
	if( piNew > 1) 
		piNew = 1;
	
	if( piNew < 0 ) 
		piNew =0;
		
	pNew <- (dexp(x,rate = 5)/0.9932621) * dbinom( 14, 24, piNew )
	
	ratio <- pNew / pOld
	
	if( ratio > 1 || ratio >= runif(1) ) 
		piOld = piNew;
		
	posteiorDist[i] = piOld;	
	
	if( i %% 100 == 0 )
	{	
		myHist <- hist(posteiorDist,breaks=200,plot=F)
		plot( myHist$mids, myHist$counts/i, main = paste("iteration", i),ylim = c(0,.04)) 
		dbetasum = sum(dbeta(myHist$mids, 40+14, 40+10))
		lines( myHist$mids, dbeta(myHist$mids, 40+14, 40+10)/dbetasum,col="red") 	
	}
}
```

```{r}
piOld <- .5
#dbeta( piOld, 40,40 )
numIterations <- 50
posteiorDist <- vector()

for( i in 1:numIterations )
{
	# our prior with 40 heads and 40 tails
	# our new data with 14 heads and 10 tails
	pOld <- (dexp(x,rate = 5)/0.9932621) * dbinom( 583, 1000, piOld )
	
	piNew <- piOld + rnorm(1, 0, sd =0.1);
	
	if( piNew > 1) 
		piNew = 1;
	
	if( piNew < 0 ) 
		piNew =0;
		
	pNew <- (dexp(x,rate = 5)/0.9932621) * dbinom( 583, 1000, piNew )
	
	ratio <- pNew / pOld
	
	if( ratio > 1 || ratio >= runif(1) ) 
		piOld = piNew;
		
	posteiorDist[i] = piOld;	
	
	if( i %% 100 == 0 )
	{	
		myHist <- hist(posteiorDist,breaks=200,plot=FALSE)
		plot( myHist$mids, myHist$counts/i, main = paste("iteration", i)) 
		dbetasum = sum(dbeta(myHist$mids, 40+583, 40+417))
		lines( myHist$mids, dbeta(myHist$mids, 40+583, 40+417)/dbetasum,col="red") 	
	}
}
```

