---
output:
  word_document: default
  html_document: default
---

```{r}
#1 What I was doing before. I will probably work on this to see if I can do a simplified version of what Connor did.
x <- 0:6
p <- .05
r <- 3
CostPerTrail <- c(1.45,1.72,2.25,2.76,3.55,4.6,5.65)
plot(x, 1 + dnbinom(x,r,p) * CostPerTrail, col = "purple")
#dn <- (dnbinom(0:7,3,.05))
#hist(x, 1-dn)
```


```{r}
#1 Connor Fraiser helped me with this. I realized that I needed to do a combination of everything we were taught which was not connecting in my head.

rm(list=ls())

CashFlow <- c(1.45,1.72,2.24,2.76,3.55,4.6,5.65,6.75)

ProbOfWin <- seq(0,1,0.01)

expected_values <- vector(length=length(ProbOfWin))

x <- 0:6

for (i in 1:length(ProbOfWin)){
    current_probs <- vector(length=length(CashFlow))
    current_exps <- vector(length=length(CashFlow))
    for (j in 1:(length(current_probs)-1)){
        current_probs[j] <- dnbinom((j-1),3,1-ProbOfWin[i])
        current_exps[j] <- current_probs[j] * CashFlow[j]
    }
    current_probs[8] <- 1-sum(current_probs[1:7])
    current_exps[8] <- current_probs[8] * CashFlow[8]
    print(current_exps)   
    expected_values[i] <- sum(current_exps)
}

plot(ProbOfWin,expected_values, col = "orange")
abline(h='3.75',col='purple')
```


```{r}
#2
rm(list=ls())

numRows = 3000
numCols = 20
for( i in 1:numCols)

myFrame <- data.frame(1:numRows)

#initiate the data.frame with the correct # of rows to suppress error messages.
#likely, there are much better ways to do this!
names(myFrame)[1] <- "tempColumn"

for( i in 1: numCols)
{
		vals <- vector(length=numRows)
		
		for( j in 1:numRows)
		{
			aMean = j /10
			aMean = max( aMean,5)
			aVar = aMean+ 5* aMean 
			aVal = round( max( rnorm(1,mean=aMean,sd=sqrt(aVar)), 1))
			vals[j] = aVal
		}
		
		colName <- paste( "sample" , i ,sep="")
		
		myFrame[[colName]] = vals
}

myFrame["tempColumn"] <- NULL
row.names(myFrame) <- paste("Gene_",1:numRows,sep="")

```

```{r}
#2A
allPValsTTest <- vector()
allPValsNegBinom <- vector()

meanReads1 = mean(apply(myFrame,2,sum)[1:5])
meanReads2 = mean(apply(myFrame,2,sum)[6:10])

for( i in 1:nrow(myFrame))
{
	vals1 <- as.numeric( myFrame[i,1:10])
	vals2 <- as.numeric( myFrame[i,11:20])
	allPValsTTest[i] = t.test( vals1,vals2)$p.value
}	

	{
	if(allPValsTTest[i] < 0.95)
		allPValsTTest[i] = 2 * allPValsTTest[i]
	else
		 allPValsTTest[i] = 2 * (1-allPValsTTest[i])
	
}
	

hist(allPValsTTest, main="t test")
```

```{r}
#2B
sum (allPValsTTest <= .05)
sum(allPValsTTest <= .05/3000)
head(sort(allPValsTTest))
```

```{r}
#2C
allPValsTCorrect <- vector ()
pVals <- sort(runif(allPValsTTest))
for (i in 1:3000)
{
  allPValsTCorrect[i] = 3000 * pVals[i]/i
}
myFrame2 <- data.frame(pVals,allPValsTCorrect)
```

```{r}
sum(myFrame2 <= .05)
```

```{r}
hist(p.adjust(allPValsTTest,method = "BH"))
p.adjust(allPValsTTest,method = "BH")
```

